name: .NET

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore net-8-isolated-azure-function-template/MyFunctionApp.sln
    - name: Build
      run: dotnet build net-8-isolated-azure-function-template/MyFunctionApp.sln --no-restore
    - name: Test
      run: dotnet test net-8-isolated-azure-function-template/MyFunctionApp.sln --no-build --verbosity normal
    - name: Publish projects
      run: |
        for project in $(find net-8-isolated-azure-function-template -name '*.csproj'); do
          dotnet publish $project -c Release -o ./publish/$(basename $project .csproj)
        done
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: published-artifact
        path: ./publish
